### ISSUE TITLE
docker system dial-stdio has exited with status 255

### ISSUE THREAD

**Issue by tcastelly** [sagebind/actions#2]
Hello,

I have a problem using your tool;

```
error during connect: Get http://docker/v1.40/info: command [ssh -l XXX-XXX -p XXX -- XXX.com docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=Host key verification failed.
```

```
 - name: Deploy to swarm
        uses: sagebind/docker-swarm-deploy-action@v2
        with:
          remote_host: ssh://XXX-XXX@XXX.com:XXX
          ssh_private_key: ${{ secrets.INFOMANIAK_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.INFOMANIAK_SSH_PUBLIC_KEY }}
          args: stack deploy --with-registry-auth --compose-file=docker-compose.yml ppp
```

It's a bit strange, I can run docker on remote like this:
> docker -H ssh://XXX-XXX@xxx.com:XXX run -ti --rm alpine /bin/sh

I guess it's a problem in my side ...
If you have an idea. 

Thanks a lot!
